export const AUTH_SIGNIN_START = "AUTH_SIGNIN_START";
export const AUTH_SIGNIN_SUCCESS = "AUTH_SIGNIN_SUCCESS";
export const AUTH_SIGNIN_FAIL = "AUTH_SIGNIN_FAIL";

export const AUTH_SIGNOUT = "AUTH_SIGNOUT";
// export const AUTH_SIGNOUT_SUCCESS = "AUTH_SIGNOUT_SUCCESS";
// export const AUTH_SIGNOUT_FAIL = "AUTH_SIGNOUT_FAIL";


export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
